---
- name: Install Git on Ubuntu
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Install Git on Amazon Linux
  ansible.builtin.dnf:
    name: git
    state: present
  when: ansible_distribution == "Amazon"
